# Site settings
title: mathieu anderhalt
email: mathieu.anderhalt@gmail.com
description: "Website under construction. Description is coming soon. "
baseurl: ""
url: "http://manderhalt.github.io/"
username: "manderhalt"

# Build settings
pygments: true
markdown: kramdown
permalink: pretty
exclude: [node_modules, Gruntfile.js, package.json]
